### ISSUE TITLE
linter: --fix leaves auto-fixable errors and exits 1 when fixes are adjacent since v1.63.0

### ISSUE THREAD

**Issue by frankeld** [oxc-project/oxc#23254]
### What version of Oxlint are you using?

1.69.0

### What command did you run?

`pnpm exec oxlint --fix repro.ts`

### What does your `.oxlintrc.json` (or `oxlint.config.ts`) config file look like?

  ```json
  {
    "jsPlugins": ["eslint-plugin-unused-imports"],
    "rules": {
      "no-unused-vars": "off",
      "unused-imports/no-unused-imports": "error"
    }
  }
  ```

### What happened?

`oxlint --fix` invocation cannot fully fix a file containing multiple *adjacent* fixable diagnostics.

### Repro

`repro.ts` — four adjacent unused imports:

```ts
import {
  pgTable,
  text,
  unique,
  index,
  foreignKey,
  check,
  jsonb,
} from "drizzle-orm/pg-core";

export const foo = pgTable("foo", {
  name: text().notNull(),
  data: jsonb(),
});
```

```
$ oxlint --fix repro.ts   # run 1
repro.ts:5:3: error unused-imports(no-unused-imports): 'index' is defined but never used.
repro.ts:7:3: error unused-imports(no-unused-imports): 'check' is defined but never used.
# exit 1 — removed `unique` and `foreignKey`, dropped the adjacent removals

$ oxlint --fix repro.ts   # run 2
repro.ts:5:3: error unused-imports(no-unused-imports): 'check' is defined but never used.
# exit 1 — `index` and `check` became adjacent after run 1, so one is dropped again

$ oxlint --fix repro.ts   # run 3
# exit 0
```

Each import-specifier removal spans its shared comma/whitespace boundary with the neighbor, so adjacent removals are treated as conflicting and only an alternating subset is applied per pass.

Probably introduced by #22071 ("treat adjacent fixes as overlapping"). ESLint pairs the same conservative overlap rule with an internal fix→relint loop.

### Expected behavior

Option to apply fixes iteratively within a single invocation until a fixed point per https://github.com/oxc-project/oxc/issues/19160#issuecomment-3868216665

**Comment by camc314** [comment]
Hi!

Thanks for reporting this issue.

Please track #16118 as it should fix this issue.

Thank you!
