### ISSUE TITLE
cannot find module '@oxlint/darwin-arm64/oxlint version: 0.15.9

### ISSUE THREAD

**Issue by imddc** [oxc-project/oxc#8856]
![Image](https://github.com/user-attachments/assets/a93a94e7-ad97-477a-8bc3-1d5149ac4b07)

i didn't test other version , but 0.11.1 running well

**Comment by Boshen** [comment]
I cannot reproduce your installation error. You can take a look at `node_modules/.pnpm/oxlint@0.15.9/node_modules/oxlint/bin/oxlint` and see whether the correct package is installed.

**Comment by jmmoser** [comment]
Works with 0.15.7 but with 0.15.8 I get:
```
Error: Cannot find module '@oxlint/linux-x64-gnu/oxlint'
```

**Comment by liunnn1994** [comment]
same issue in `0.15.9`:
``` bash
❯ node -v
v22.13.1
❯ pnpm -v
10.2.0
```
back to `0.15.7` can solve the problem for now.

**Comment by liunnn1994** [comment]
Independent of the pnpm:

> Use the latest version

``` powershell
❯ npx oxlint -V

node:internal/modules/cjs/loader:1247
  throw err;
  ^

Error: Cannot find module '@oxlint/win32-x64/oxlint.exe'
Require stack:
- C:\Users\xxx\AppData\Local\npm-cache\_npx\35625a6d79362d8c\node_modules\oxlint\bin\oxlint
    at Function._resolveFilename (node:internal/modules/cjs/loader:1244:15)
    at Function.resolve (node:internal/modules/helpers:146:19)
    at Object.<anonymous> (C:\Users\xxx\AppData\Local\npm-cache\_npx\35625a6d79362d8c\node_modules\oxlint\bin\oxlint:102:13)
    at Module._compile (node:internal/modules/cjs/loader:1562:14)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\xxx\\AppData\\Local\\npm-cache\\_npx\\35625a6d79362d8c\\node_modules\\oxlint\\bin\\oxlint'
  ]
}

Node.js v22.13.1
```

> Use 0.15.7

``` powershell
❯ npx oxlint@0.15.7 -V
Version: 0.15.7
```

The `@oxlint` folder is empty

![Image](https://github.com/user-attachments/assets/951f1f9b-0efa-451d-bcd3-3fffcc55930e)

**Comment by Sysix** [comment]
@Boshen maybe the same old problem with the CI?

Some platform-packages are published later by npm 
and in the time someone can use `npm update oxlint` and do not get all platform sub packages. 

can someone try to use following commands and report if this fix the problem? 
```
npm uninstall oxlint
npm cache clear --force
npm install --save-dev oxlint
npmx oxlint
```

The binaries should be published:
- https://registry.npmjs.org/@oxlint%2fdarwin-x64/0.15.9
- https://registry.npmjs.org/@oxlint%2fwin32-x64/0.15.9

Try to download the `taz` file und unpack it with `tar -xvzf`

**Comment by Boshen** [comment]
Please let us know if the problem persists in https://github.com/oxc-project/oxc/releases/tag/oxlint_v0.15.10

I added a time [3 minutes sleep] before publishing the main package https://github.com/oxc-project/oxc/commit/e453be4bf22d285a34825652a7a1d20b3fdf7121
